function [BW,maskedImage] = segmentImage(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 28-Mar-2020
%----------------------------------------------------


% Normalize input data to range in [0,1].
Xmin = min(X(:));
Xmax = max(X(:));
if isequal(Xmax,Xmin)
    X = 0*X;
else
    X = (X - Xmin) ./ (Xmax - Xmin);
end

% Threshold image - manual threshold
BW = X > 12.5e-02;

% Open mask with disk
radius = 2;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imopen(BW, se);

% % Erode mask with disk
% radius = 1;
% decomposition = 0;
% se = strel('disk', radius, decomposition);
% BW = imerode(BW, se);
% 
% % Open mask with disk
% radius = 2;
% decomposition = 0;
% se = strel('disk', radius, decomposition);
% BW = imopen(BW, se);

% % Dilate mask with disk
% radius = 3;
% decomposition = 0;
% se = strel('disk', radius, decomposition);
% BW = imdilate(BW, se);
% 
% % Erode mask with disk
% radius = 2;
% decomposition = 0;
% se = strel('disk', radius, decomposition);
% BW = imerode(BW, se);
% 
% % Open mask with disk
% radius = 3;
% decomposition = 0;
% se = strel('disk', radius, decomposition);
% BW = imopen(BW, se);

% % Erode mask with disk
% radius = 4;
% decomposition = 0;
% se = strel('disk', radius, decomposition);
% BW = imerode(BW, se);
% 
% % Open mask with disk
% radius = 1;
% decomposition = 0;
% se = strel('disk', radius, decomposition);
% BW = imopen(BW, se);
% 
% % Dilate mask with disk
% radius = 2;
% decomposition = 0;
% se = strel('disk', radius, decomposition);
% BW = imdilate(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

