function [BW,maskedImage] = segmentImage115_20210629_rewBehaviorETA_20231219zScored(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 19-Dec-2023
%----------------------------------------------------


% Normalize input data to range in [0,1].
Xmin = min(X(:));
Xmax = max(X(:));
if isequal(Xmax,Xmin)
    X = 0*X;
else
    X = (X - Xmin) ./ (Xmax - Xmin);
end

% Threshold image with global threshold
BW = imbinarize(im2gray(X));

% Active contour
iterations = 2;
BW = activecontour(X, BW, iterations, 'edge');

% Dilate mask with default
radius = 3;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Active contour
iterations = 1;
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Dilate mask with line
length = 4.000000;
angle = 45.000000;
se = strel('line', length, angle);
BW = imdilate(BW, se);

% Active contour
iterations = 4;
BW = activecontour(X, BW, iterations, 'edge');

% Open mask with default
radius = 1;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imopen(BW, se);

% Dilate mask with default
radius = 3;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Active contour
iterations = 1;
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Dilate mask with line
length = 4.000000;
angle = 45.000000;
se = strel('line', length, angle);
BW = imdilate(BW, se);

% Active contour
iterations = 5;
BW = activecontour(X, BW, iterations, 'edge');

% Active contour
iterations = 10;
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Active contour
iterations = 3;
BW = activecontour(X, BW, iterations, 'edge');

% Dilate mask with default
radius = 3;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Active contour
iterations = 1;
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Dilate mask with line
length = 4.000000;
angle = 45.000000;
se = strel('line', length, angle);
BW = imdilate(BW, se);

% Active contour
iterations = 4;
BW = activecontour(X, BW, iterations, 'edge');

% Erode mask with default
radius = 1;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Dilate mask with default
radius = 3;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Active contour
iterations = 1;
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Dilate mask with line
length = 4.000000;
angle = 45.000000;
se = strel('line', length, angle);
BW = imdilate(BW, se);


% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

